<a href="https://colab.research.google.com/github/poncedanna08-rgb/AYP-2026/blob/main/CLASE_AYP_06_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manejo de Datos Numericos


In [ ]:
import time
lista = list(range (10000000))
inicio = time.time()
[valor * 2 for valor in lista]
print ("Tiempo de ejecucion con listas: ", time.time()-inicio)

Tiempo de ejecucion con listas:  0.6774969100952148


In [ ]:
import numpy as np
arreglo = np.arange(10000000)
inicio = time.time()
arreglo * 2
print ("Tiempo de ejecucion con listas: ", time.time()-inicio)

Tiempo de ejecucion con listas:  0.02422618865966797


Instalacion y Uso Basico


In [ ]:
!pip install numpy

Arreglos en Numpy

In [ ]:
import numpy as np
arreglo = np.array ([1,2,3,4], dtype = float)
print (arreglo)

[1. 2. 3. 4.]


Dimensiones y Formas de los Arreglos

In [ ]:
print("El numero de dimensiones del arreglo es: ", arreglo.ndim)
print ("La forma del arreglo es: ", arreglo.shape)
print ("El total de elementos en el arreglo es: ", arreglo.size)
print ("Los tipos de datos en el arreglo son: ", arreglo.dtype)

El numero de dimensiones del arreglo es:  1
La forma del arreglo es:  (4,)
El total de elementos en el arreglo es:  4
Los tipos de datos en el arreglo son:  float64


In [ ]:
arreglo_2d = np.array([[1,2,3],[4,5,6]])
print(arreglo_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("El numero de dimensiones del arreglo es: ", arreglo_2d.ndim)
print ("La forma del arreglo es: ", arreglo_2d.shape)
print ("El total de elementos en el arreglo es: ", arreglo_2d.size)
print ("Los tipos de datos en el arreglo son: ", arreglo_2d.dtype)

El numero de dimensiones del arreglo es:  2
La forma del arreglo es:  (2, 3)
El total de elementos en el arreglo es:  6
Los tipos de datos en el arreglo son:  int64


In [ ]:
arreglo_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
arreglo_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
print("El numero de dimensiones del arreglo es: ", arreglo_3d.ndim)
print ("La forma del arreglo es: ", arreglo_3d.shape)
print ("El total de elementos en el arreglo es: ", arreglo_3d.size)
print ("Los tipos de datos en el arreglo son: ", arreglo_3d.dtype)

El numero de dimensiones del arreglo es:  3
La forma del arreglo es:  (1, 4, 3)
El total de elementos en el arreglo es:  12
Los tipos de datos en el arreglo son:  int64


Otros Arreglos

In [ ]:
ceros = np.zeros((2,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
vacio = np.empty((6,5))
vacio

array([[5.16701045e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.63041663e-322,
        6.62192157e-310, 6.62192157e-310]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.rand(2,3,1)

array([[[0.55136301],
        [0.3127956 ],
        [0.36696185]],

       [[0.81150277],
        [0.43397416],
        [0.48491223]]])

Valores Numericos Especiales


In [ ]:
arreglo1 = np.array([[1,0],[-1,1]])
print(arreglo1)

[[ 1  0]
 [-1  1]]


In [ ]:
arreglo1 / 0

/tmp/ipykernel_2022/1539411815.py:1: RuntimeWarning: divide by zero encountered in divide
  arreglo1 / 0
/tmp/ipykernel_2022/1539411815.py:1: RuntimeWarning: invalid value encountered in divide
  arreglo1 / 0


array([[ inf,  nan],
       [-inf,  inf]])

In [ ]:
arreglo2 = np.array([[np.inf, np.nan]])
arreglo2

array([[inf, nan]])

In [ ]:
array_inf = np.array([1, 2.5])**5
print(array_inf)

[ 1.      97.65625]
