<a href="https://colab.research.google.com/github/poncedanna08-rgb/AYP-2026/blob/main/CLASE_AYP_08_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**clase 08/05/2026**


*   Brigadas, indexacion
*   Aritmetica y Operadores con arreglos
*   Adecuacion de la forma de Arreglos (metodo np.ndarray.*reshape()*)
*   metodo transpose()



In [2]:
import numpy as np

In [3]:
brigadas = np.array ([[["Juan", "Antonio", "Ricardo"], ["Alonso", "Jorge", "Salvador"]],
                      [["David", "Julian", "Ricardo"], ["Arturo", "Ramiro", "Esteban"]],
                      [["Arturo", "Ricardo", "Lucio"], ["Jorge", "Marco", "Juan"]],
                      [["Alonso", "Julian", "Salvador"], ["Ricardo", "Jorge", "Esteban"]],
                      [["Lucio", "Ramiro", "Joaquin"], ["Jorge", "Marco", "Juan"]]])

In [4]:
brigadas

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramiro', 'Joaquin'],
        ['Jorge', 'Marco', 'Juan']]], dtype='<U8')

In [5]:
brigadas[1:3,:,:]

array([[['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']]], dtype='<U8')

In [6]:
brigadas[1:3,:,:].shape

(2, 2, 3)

In [7]:
brigadas[:, 1, 0:2]

array([['Alonso', 'Jorge'],
       ['Arturo', 'Ramiro'],
       ['Jorge', 'Marco'],
       ['Ricardo', 'Jorge'],
       ['Jorge', 'Marco']], dtype='<U8')

In [8]:
brigadas[:, 1, 0:2].shape

(5, 2)

In [9]:
brigadas[4, 0, 1]

np.str_('Ramiro')

In [10]:
type(brigadas[4,0,1])

numpy.str_

In [11]:
sustitutos = np.array([["John", "Ringo", "Paul"],
                        ["Keith", "Mick", "Charlie"]])

In [12]:
sustitutos.shape

(2, 3)

In [13]:
brigadas.shape

(5, 2, 3)

In [14]:
brigadas

array([[['Juan', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['David', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramiro', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Juan']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramiro', 'Joaquin'],
        ['Jorge', 'Marco', 'Juan']]], dtype='<U8')

In [17]:
brigadas[4, 1, 2] = "Pascual"

In [18]:
matriz_1 = np.array([[1, 2, 3],
                     [4, 0, -5],
                     [-6, -7, -8]])

In [19]:
matriz_1[2, :] * 3

array([-18, -21, -24])

In [20]:
matriz_1 + 100

array([[101, 102, 103],
       [104, 100,  95],
       [ 94,  93,  92]])

In [21]:
3 / matriz_1

/tmp/ipykernel_10558/113740686.py:1: RuntimeWarning: divide by zero encountered in divide
  3 / matriz_1


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf, -0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [23]:
matriz_1 > 1

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [22]:
matriz_1 / 2


array([[ 0.5,  1. ,  1.5],
       [ 2. ,  0. , -2.5],
       [-3. , -3.5, -4. ]])

In [24]:
matriz_1.shape


(3, 3)

In [25]:
matriz_2 = np.array[(1, 2, 3)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [29]:
matriz_2 = np.array((1, 2, 3))
matriz_2.shape

(3,)

In [ ]:
import numpy as np
arreglo_2 = np.array ([[]])

In [ ]:
#El resize es parecido al reshape, pero llena con 0 los demas datos.

In [33]:
matriz_1 * matriz_2

array([[  1,   4,   9],
       [  4,   0, -15],
       [ -6, -14, -24]])

In [34]:
matriz_3 = np.array([[2], [4], [6]])

In [35]:
matriz_3

array([[2],
       [4],
       [6]])

In [36]:
matriz_3.shape

(3, 1)

In [37]:
matriz_3 * matriz_1

array([[  2,   4,   6],
       [ 16,   0, -20],
       [-36, -42, -48]])

In [38]:
arreglo_2 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])

In [39]:
arreglo_2.shape

(3, 4)

In [40]:
arreglo_2.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [41]:
arreglo_2.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
arreglo_2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
np.reshape(arreglo_2,(1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [44]:
np.reshape(arreglo_2,(12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [45]:
arreglo_3 = np.array([[1,2],
                      [3,4]])

In [46]:
arreglo_3.shape

(2, 2)

In [47]:
arreglo_3.resize(3, 3, 2)

In [48]:
arreglo_3

array([[[1, 2],
        [3, 4],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [49]:
arreglo_4 = np.array([[1,2],
                      [3, 4]])

In [50]:
arreglo_4.shape

(2, 2)

In [51]:
np.resize(arreglo_4,(2, 3, 2))

array([[[1, 2],
        [3, 4],
        [1, 2]],

       [[3, 4],
        [1, 2],
        [3, 4]]])

In [52]:
arreglo_4

array([[1, 2],
       [3, 4]])

In [53]:
np.resize(arreglo_4,(2))

array([1, 2])

In [65]:
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [66]:
matriz.shape

(3, 4)

In [67]:
matriz.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [68]:
matriz.transpose().shape

(4, 3)

In [69]:
matriz_T = np.transpose(matriz)

In [70]:
matriz_T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [71]:
origen = np.arange(9).reshape(3, 3, 1)

In [72]:
origen

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [73]:
np.squeeze(origen, 2)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
np.squeeze(origen, 2).shape

(3, 3)

In [75]:
arreglo_1 = np.array([[1, 2],
                      [3, 4]])

In [76]:
arreglo_1

array([[1, 2],
       [3, 4]])

In [77]:
arreglo_2 = np.array([[5, 6],
                      [7, 8]])

In [78]:
np.concatenate((arreglo_1, arreglo_2), 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [79]:
arreglo_original = np.arange(9).reshape(3, 3)

In [80]:
arreglo_original

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
arreglo_eje_0 = np.array([[5, 6, 7], [8, 9, 10]])

In [82]:
arreglo_eje_0

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [83]:
arreglo_eje_0.shape

(2, 3)

In [84]:
np.append(arreglo_original, arreglo_eje_0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  5,  6,  7,  8,  9, 10])

In [85]:
np.append(arreglo_original, arreglo_eje_0, axis=0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [86]:
arreglo_eje_1 = np.arange(7, 13).reshape(3, 2)

In [87]:
arreglo_eje_1

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [88]:
np.append(arreglo_original, arreglo_eje_1, axis=1)

array([[ 0,  1,  2,  7,  8],
       [ 3,  4,  5,  9, 10],
       [ 6,  7,  8, 11, 12]])